# Generated by Django 2.0.1 on 2018-02-01 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('carMake', models.CharField(blank=True, max_length=20)),
                ('carModel', models.CharField(blank=True, max_length=50)),
                ('carYear', models.CharField(blank=True, max_length=4)),
                ('stereoMake', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('isFeatured', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete='CASCADE', related_name='images', to='oa.Project')),
            ],
        ),
    ]
