# Generated by Django 2.0.1 on 2018-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featuredImage',
            field=models.ImageField(default='/static/img/project.jpg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
