# Generated by Django 2.0.1 on 2018-02-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0002_project_featuredimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbImage',
            field=models.ImageField(default='/static/img/project.jpg', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
