# Generated by Django 2.0.1 on 2018-02-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0003_auto_20180202_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbImage',
            field=models.ImageField(blank=True, default='/static/img/project.jpg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
