# Generated by Django 2.0.1 on 2018-02-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0004_auto_20180202_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt_text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectimages',
            name='alt_text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
